In [7]:
import pandas as pd # Import the pandas library and give it the alias 'pd'

df = pd.read_csv('/content/drive/MyDrive/data.csv') # Now you can use pd to refer to pandas
df

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,month,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,34579,35.0,admin.,single,university.degree,no,yes,no,cellular,may,...,1,999.0,1.0,failure,-1.8,92.893,-46.2,1.266,5099.1,no
1,446,42.0,technician,married,professional.course,no,no,no,telephone,may,...,1,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,yes
2,20173,36.0,admin.,married,university.degree,no,no,no,cellular,aug,...,2,999.0,0.0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,yes
3,18171,37.0,admin.,married,high.school,no,yes,yes,telephone,jul,...,2,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,yes
4,30128,31.0,management,single,university.degree,no,yes,no,cellular,apr,...,1,999.0,0.0,nonexistent,-1.8,93.075,-47.1,1.365,5099.1,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9275,28870,45.0,blue-collar,married,unknown,no,yes,no,cellular,apr,...,1,999.0,1.0,failure,-1.8,93.075,-47.1,1.410,5099.1,yes
9276,30452,NaN,admin.,married,university.degree,no,yes,no,cellular,may,...,2,999.0,0.0,nonexistent,-1.8,92.893,-46.2,1.354,5099.1,yes
9277,28937,38.0,blue-collar,married,basic.9y,no,yes,no,cellular,apr,...,1,999.0,1.0,failure,-1.8,93.075,-47.1,1.405,5099.1,no
9278,16739,41.0,technician,single,university.degree,no,no,no,cellular,jul,...,2,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
9279,16807,56.0,services,married,high.school,unknown,yes,no,telephone,jul,...,11,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no

In [8]:
print(df.columns)

Index(['Unnamed: 0', 'age', 'job', 'marital', 'education', 'default',
       'housing', 'loan', 'contact', 'month', 'day_of_week', 'duration',
       'campaign', 'pdays', 'previous', 'poutcome', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [9]:
df = pd.get_dummies(df, columns=['housing'])

df

,Unnamed: 0,age,job,marital,education,default,loan,contact,month,day_of_week,...,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,housing_no,housing_unknown,housing_yes
0,34579,35.0,admin.,single,university.degree,no,no,cellular,may,thu,...,failure,-1.8,92.893,-46.2,1.266,5099.1,no,False,False,True
1,446,42.0,technician,married,professional.course,no,no,telephone,may,tue,...,nonexistent,1.1,93.994,-36.4,4.857,5191.0,yes,True,False,False
2,20173,36.0,admin.,married,university.degree,no,no,cellular,aug,mon,...,nonexistent,1.4,93.444,-36.1,4.965,5228.1,yes,True,False,False
3,18171,37.0,admin.,married,high.school,no,yes,telephone,jul,wed,...,nonexistent,1.4,93.918,-42.7,4.963,5228.1,yes,False,False,True
4,30128,31.0,management,single,university.degree,no,no,cellular,apr,thu,...,nonexistent,-1.8,93.075,-47.1,1.365,5099.1,no,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9275,28870,45.0,blue-collar,married,unknown,no,no,cellular,apr,thu,...,failure,-1.8,93.075,-47.1,1.410,5099.1,yes,False,False,True
9276,30452,NaN,admin.,married,university.degree,no,no,cellular,may,mon,...,nonexistent,-1.8,92.893,-46.2,1.354,5099.1,yes,False,False,True
9277,28937,38.0,blue-collar,married,basic.9y,no,no,cellular,apr,fri,...,failure,-1.8,93.075,-47.1,1.405,5099.1,no,False,False,True
9278,16739,41.0,technician,single,university.degree,no,no,cellular,jul,thu,...,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no,True,False,False
9279,16807,56.0,services,married,high.school,unknown,no,telephone,jul,thu,...,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no,False,False,True

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['job']=le.fit_transform(df['job'])
df

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,month,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,34579,35.0,0,single,university.degree,no,yes,no,cellular,may,...,1,999.0,1.0,failure,-1.8,92.893,-46.2,1.266,5099.1,no
1,446,42.0,9,married,professional.course,no,no,no,telephone,may,...,1,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,yes
2,20173,36.0,0,married,university.degree,no,no,no,cellular,aug,...,2,999.0,0.0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,yes
3,18171,37.0,0,married,high.school,no,yes,yes,telephone,jul,...,2,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,yes
4,30128,31.0,4,single,university.degree,no,yes,no,cellular,apr,...,1,999.0,0.0,nonexistent,-1.8,93.075,-47.1,1.365,5099.1,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9275,28870,45.0,1,married,unknown,no,yes,no,cellular,apr,...,1,999.0,1.0,failure,-1.8,93.075,-47.1,1.410,5099.1,yes
9276,30452,NaN,0,married,university.degree,no,yes,no,cellular,may,...,2,999.0,0.0,nonexistent,-1.8,92.893,-46.2,1.354,5099.1,yes
9277,28937,38.0,1,married,basic.9y,no,yes,no,cellular,apr,...,1,999.0,1.0,failure,-1.8,93.075,-47.1,1.405,5099.1,no
9278,16739,41.0,9,single,university.degree,no,no,no,cellular,jul,...,2,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
9279,16807,56.0,7,married,high.school,unknown,yes,no,telephone,jul,...,11,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no

In [14]:
from sklearn.preprocessing import OrdinalEncoder
size_mapping = {'tertiary':0, 'secondary':1, 'unknown':2}
df['education']=df['education'].map(size_mapping)
df

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,month,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,34579,35.0,0,single,NaN,no,yes,no,cellular,may,...,1,999.0,1.0,failure,-1.8,92.893,-46.2,1.266,5099.1,no
1,446,42.0,9,married,NaN,no,no,no,telephone,may,...,1,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,yes
2,20173,36.0,0,married,NaN,no,no,no,cellular,aug,...,2,999.0,0.0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,yes
3,18171,37.0,0,married,NaN,no,yes,yes,telephone,jul,...,2,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,yes
4,30128,31.0,4,single,NaN,no,yes,no,cellular,apr,...,1,999.0,0.0,nonexistent,-1.8,93.075,-47.1,1.365,5099.1,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9275,28870,45.0,1,married,2.0,no,yes,no,cellular,apr,...,1,999.0,1.0,failure,-1.8,93.075,-47.1,1.410,5099.1,yes
9276,30452,NaN,0,married,NaN,no,yes,no,cellular,may,...,2,999.0,0.0,nonexistent,-1.8,92.893,-46.2,1.354,5099.1,yes
9277,28937,38.0,1,married,NaN,no,yes,no,cellular,apr,...,1,999.0,1.0,failure,-1.8,93.075,-47.1,1.405,5099.1,no
9278,16739,41.0,9,single,NaN,no,no,no,cellular,jul,...,2,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
9279,16807,56.0,7,married,NaN,unknown,yes,no,telephone,jul,...,11,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no

In [15]:
frequency_encoding = df['job'].value_counts().to_dict()
df['job'] =df['job'].map(frequency_encoding)
df

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,month,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,34579,35.0,2561,single,NaN,no,yes,no,cellular,may,...,1,999.0,1.0,failure,-1.8,92.893,-46.2,1.266,5099.1,no
1,446,42.0,1475,married,NaN,no,no,no,telephone,may,...,1,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,yes
2,20173,36.0,2561,married,NaN,no,no,no,cellular,aug,...,2,999.0,0.0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,yes
3,18171,37.0,2561,married,NaN,no,yes,yes,telephone,jul,...,2,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,yes
4,30128,31.0,653,single,NaN,no,yes,no,cellular,apr,...,1,999.0,0.0,nonexistent,-1.8,93.075,-47.1,1.365,5099.1,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9275,28870,45.0,1734,married,2.0,no,yes,no,cellular,apr,...,1,999.0,1.0,failure,-1.8,93.075,-47.1,1.410,5099.1,yes
9276,30452,NaN,2561,married,NaN,no,yes,no,cellular,may,...,2,999.0,0.0,nonexistent,-1.8,92.893,-46.2,1.354,5099.1,yes
9277,28937,38.0,1734,married,NaN,no,yes,no,cellular,apr,...,1,999.0,1.0,failure,-1.8,93.075,-47.1,1.405,5099.1,no
9278,16739,41.0,1475,single,NaN,no,no,no,cellular,jul,...,2,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
9279,16807,56.0,780,married,NaN,unknown,yes,no,telephone,jul,...,11,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no

In [19]:
mean_encoded = df.groupby('job')['education'].mean().to_dict()
df['job'] = df['job'].map(mean_encoded)
df

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,month,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,34579,35.0,2.0,single,NaN,no,yes,no,cellular,may,...,1,999.0,1.0,failure,-1.8,92.893,-46.2,1.266,5099.1,no
1,446,42.0,2.0,married,NaN,no,no,no,telephone,may,...,1,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,yes
2,20173,36.0,2.0,married,NaN,no,no,no,cellular,aug,...,2,999.0,0.0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,yes
3,18171,37.0,2.0,married,NaN,no,yes,yes,telephone,jul,...,2,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,yes
4,30128,31.0,2.0,single,NaN,no,yes,no,cellular,apr,...,1,999.0,0.0,nonexistent,-1.8,93.075,-47.1,1.365,5099.1,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9275,28870,45.0,2.0,married,2.0,no,yes,no,cellular,apr,...,1,999.0,1.0,failure,-1.8,93.075,-47.1,1.410,5099.1,yes
9276,30452,NaN,2.0,married,NaN,no,yes,no,cellular,may,...,2,999.0,0.0,nonexistent,-1.8,92.893,-46.2,1.354,5099.1,yes
9277,28937,38.0,2.0,married,NaN,no,yes,no,cellular,apr,...,1,999.0,1.0,failure,-1.8,93.075,-47.1,1.405,5099.1,no
9278,16739,41.0,2.0,single,NaN,no,no,no,cellular,jul,...,2,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
9279,16807,56.0,2.0,married,NaN,unknown,yes,no,telephone,jul,...,11,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no

In [20]:
df['marital'] = df['marital'].astype(str)
df

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,month,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,34579,35.0,2.0,single,NaN,no,yes,no,cellular,may,...,1,999.0,1.0,failure,-1.8,92.893,-46.2,1.266,5099.1,no
1,446,42.0,2.0,married,NaN,no,no,no,telephone,may,...,1,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,yes
2,20173,36.0,2.0,married,NaN,no,no,no,cellular,aug,...,2,999.0,0.0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,yes
3,18171,37.0,2.0,married,NaN,no,yes,yes,telephone,jul,...,2,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,yes
4,30128,31.0,2.0,single,NaN,no,yes,no,cellular,apr,...,1,999.0,0.0,nonexistent,-1.8,93.075,-47.1,1.365,5099.1,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9275,28870,45.0,2.0,married,2.0,no,yes,no,cellular,apr,...,1,999.0,1.0,failure,-1.8,93.075,-47.1,1.410,5099.1,yes
9276,30452,NaN,2.0,married,NaN,no,yes,no,cellular,may,...,2,999.0,0.0,nonexistent,-1.8,92.893,-46.2,1.354,5099.1,yes
9277,28937,38.0,2.0,married,NaN,no,yes,no,cellular,apr,...,1,999.0,1.0,failure,-1.8,93.075,-47.1,1.405,5099.1,no
9278,16739,41.0,2.0,single,NaN,no,no,no,cellular,jul,...,2,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
9279,16807,56.0,2.0,married,NaN,unknown,yes,no,telephone,jul,...,11,999.0,0.0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no

In [21]:
import pandas as pd
from sklearn.feature_extraction import FeatureHasher

# Sample DataFrame with potential missing values
data = {
    'marital': ['single', 'married', 'divorced', 'married', 'single', None],
    'loan': [1, 0, 1, 0, 0, 1]
}

df = pd.DataFrame(data)
df

    marital  loan
0    single     1
1   married     0
2  divorced     1
3   married     0
4    single     0
5      None     1

In [22]:
marital_list = df['marital'].apply(lambda x: [x]).tolist()
df

    marital  loan
0    single     1
1   married     0
2  divorced     1
3   married     0
4    single     0
5      None     1

In [27]:
from sklearn.feature_extraction import FeatureHasher
import pandas as pd
marital_list = ['married', 'single', 'divorced', 'married', 'widowed']
marital_list = [{'marital_status': status} for status in marital_list]
hasher = FeatureHasher(input_type='dict', n_features=8)
hashed_features = hasher.transform(marital_list)
df_hashed = pd.DataFrame(hashed_features.toarray(), columns=[f'marital_{i}' for i in range(8)])
print(df_hashed)

   marital_0  marital_1  marital_2  marital_3  marital_4  marital_5  \
0        0.0        0.0        0.0        0.0        0.0        0.0
1        0.0        0.0        1.0        0.0        0.0        0.0
2        0.0        0.0        1.0        0.0        0.0        0.0
3        0.0        0.0        0.0        0.0        0.0        0.0
4        0.0       -1.0        0.0        0.0        0.0        0.0

   marital_6  marital_7
0        0.0        1.0
1        0.0        0.0
2        0.0        0.0
3        0.0        1.0
4        0.0        0.0